### ISSUE TITLE
property scrollIntoView - object is null or undefined

### ISSUE THREAD

**Issue by guntiso** [kveeiv/extjs-boxselect#16]
v2.0.3, IE:
SCRIPT5007: Unable to get value of the property 'scrollIntoView': object is null or undefined 
BoxSelect.js, line 1094 character 17

This sometimes happens when closing popup on IE. The line is:

me.inputElCt.scrollIntoView(me.listWrapper);

**Comment by kveeiv** [comment]
Thanks for the report! This will be fixed in commit 06e3c22 (not pushed to github yet) as well as be included in the next maintenance release.
