### ISSUE TITLE
Ext JS 4.1 issue

### ISSUE THREAD

**Issue by darrenkan** [kveeiv/extjs-boxselect#7]
Hi,

I am testing boxSelect with ExtJS 4.1 RC3, it works in Firefox and Chrome. But it prompts error when using in IE, could you pls help? Thanks.

Object doesn't support this property or method

dom.addEventListener(bind.eventName, wrap, options.capture || false);

Thanks and Regards,
Darren

**Comment by Reimius** [comment]
Which version of IE?  I have noticed that in IE9 this issue is fixed by using the standards mode doctype (Extjs 4.1 seems to detect IE9 as IE8 when IE9 is in quirks mode for some reason).  This is inline with the fact that Extjs doesn't officially support quirks mode in IE anywsay.  I would like to know if you are experiencing this on a lower version for my personal records though...

**Comment by darrenkan** [comment]
I am using IE7...

**Comment by moritori** [comment]
Have a look at my fork at https://github.com/moritori/extjs-boxselect. The latest version should fix your problem (I encountered the exactly same problem and found the time to fix it).

**Comment by Reimius** [comment]
moritori, I have some extras and fixes for this component also.  Can you give me a short explanation of how to do a pull request on your project?  Do you have to use Git to get the code, update it and then commit as a pull request?  One of the main things I think people would benefit from is my fixes to pasting into this field, and also I have added a search box that filters results on the left side.

**Comment by Reimius** [comment]
Oops, I got confused here.  Ignore the comment about the search box, this only thing I did for this component was to fix pasting issues and value splitting in the onKeyUp method.

**Comment by moritori** [comment]
Hey Reimius, I'm willing to look into your code. Just fork my repository, commit your changes to your fork and send me a pull request with your changes. And please describe (e.g. open an issue for the broken part), what you're trying to fix. Thanks.

**Comment by kveeiv** [comment]
I've incorporated much of moritori's efforts made in pull request 10 which I think might resolve the original issue here. Unfortunately I do not have access to an IE7 environment to be able to verify that these changes fixed this problem. If you are still able to replicate this issue in the extjs-boxselect-2.0.0 release and are able to provide a pull request to resolve it, I would be happy to include those changes.
